# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimerXdd.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(227, 148)
        self.label_date = QtWidgets.QLabel(Form)
        self.label_date.setGeometry(QtCore.QRect(100, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_date.setFont(font)
        self.label_date.setText("")
        self.label_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 231, 128))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_jishi = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_jishi.setGeometry(QtCore.QRect(40, 10, 111, 28))
        self.textBrowser_jishi.setObjectName("textBrowser_jishi")
        self.pushButton_start1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_start1.setGeometry(QtCore.QRect(10, 40, 81, 28))
        self.pushButton_start1.setObjectName("pushButton_start1")
        self.pushButton_pause1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_pause1.setGeometry(QtCore.QRect(110, 40, 81, 28))
        self.pushButton_pause1.setObjectName("pushButton_pause1")
        self.pushButton_clean1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_clean1.setGeometry(QtCore.QRect(10, 70, 81, 28))
        self.pushButton_clean1.setObjectName("pushButton_clean1")
        self.pushButton_cleanAndStart1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_cleanAndStart1.setGeometry(QtCore.QRect(110, 70, 81, 28))
        self.pushButton_cleanAndStart1.setObjectName("pushButton_cleanAndStart1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_minute_2 = QtWidgets.QLabel(self.tab_2)
        self.label_minute_2.setGeometry(QtCore.QRect(50, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_minute_2.setFont(font)
        self.label_minute_2.setObjectName("label_minute_2")
        self.textBrowser_daojishi = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_daojishi.setGeometry(QtCore.QRect(90, 10, 101, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_daojishi.setFont(font)
        self.textBrowser_daojishi.setObjectName("textBrowser_daojishi")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(12, 10, 31, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_start2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_start2.setGeometry(QtCore.QRect(12, 40, 81, 28))
        self.pushButton_start2.setObjectName("pushButton_start2")
        self.pushButton_pause2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_pause2.setGeometry(QtCore.QRect(110, 40, 81, 28))
        self.pushButton_pause2.setObjectName("pushButton_pause2")
        self.pushButton_clean2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_clean2.setGeometry(QtCore.QRect(12, 70, 81, 28))
        self.pushButton_clean2.setObjectName("pushButton_clean2")
        self.pushButton_cleanAndStart2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_cleanAndStart2.setGeometry(QtCore.QRect(110, 70, 80, 28))
        self.pushButton_cleanAndStart2.setObjectName("pushButton_cleanAndStart2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_start1.setText(_translate("Form", "开始"))
        self.pushButton_pause1.setText(_translate("Form", "暂停"))
        self.pushButton_clean1.setText(_translate("Form", "清零"))
        self.pushButton_cleanAndStart1.setText(_translate("Form", "清零并开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "计时器"))
        self.label_minute_2.setText(_translate("Form", "分钟"))
        self.pushButton_start2.setText(_translate("Form", "开始"))
        self.pushButton_pause2.setText(_translate("Form", "暂停"))
        self.pushButton_clean2.setText(_translate("Form", "清零"))
        self.pushButton_cleanAndStart2.setText(_translate("Form", "清零并开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "倒计时"))
