# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RandomNum_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(666, 445)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 40, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textdisplay = QtWidgets.QTextBrowser(Form)
        self.textdisplay.setGeometry(QtCore.QRect(290, 120, 321, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textdisplay.setFont(font)
        self.textdisplay.setObjectName("textdisplay")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 130, 181, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.editMin = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editMin.setFont(font)
        self.editMin.setObjectName("editMin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editMin)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.editMax = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editMax.setFont(font)
        self.editMax.setObjectName("editMax")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editMax)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.editCounter = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editCounter.setFont(font)
        self.editCounter.setObjectName("editCounter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editCounter)
        self.rbtnChongFu = QtWidgets.QRadioButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbtnChongFu.setFont(font)
        self.rbtnChongFu.setObjectName("rbtnChongFu")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rbtnChongFu)
        self.rbtnSingle = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rbtnSingle.setEnabled(True)
        self.rbtnSingle.setObjectName("rbtnSingle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rbtnSingle)
        self.btnCreat = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCreat.setFont(font)
        self.btnCreat.setObjectName("btnCreat")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.btnCreat)
        self.btnClear = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnClear)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(70, 120, 201, 151))
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.label.raise_()
        self.textdisplay.raise_()
        self.formLayoutWidget.raise_()

        self.retranslateUi(Form)
        self.btnClear.clicked.connect(self.textdisplay.clear)
        self.btnCreat.clicked.connect(Form.btnCreat_click)
        self.editCounter.editingFinished.connect(Form.editCounter_Finish)
        self.editCounter.textChanged['QString'].connect(Form.editCounter_Finish)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "随机数产生工具"))
        self.textdisplay.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">展示区</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "最小值"))
        self.label_3.setText(_translate("Form", "最大值"))
        self.label_4.setText(_translate("Form", "生成个数"))
        self.rbtnChongFu.setText(_translate("Form", "可重复"))
        self.rbtnSingle.setText(_translate("Form", "单一值"))
        self.btnCreat.setText(_translate("Form", "生成"))
        self.btnClear.setText(_translate("Form", "清除"))
